#' Batch ROUT Outlier Detection for Dose–Response Plates
#'
#' @description
#' Applies ROUT-based outlier detection (via \code{rout_outliers()}) across
#' multiple plates contained in a batch object. Each plate is processed
#' independently, and results are aggregated into summary tables.
#'
#' This function is designed to operate on outputs from
#' \code{ratio_dose_response_v2()}, specifically the
#' \code{modified_ratio_table} element stored within each plate.
#'
#' @details
#' The function iterates over a named list of plate results, where each element
#' is expected to contain a processed dose–response table.
#'
#' For each plate:
#' \itemize{
#'   \item Removes empty or invalid columns (e.g., NA-only compounds)
#'   \item Separates control rows (NA concentration) from dose rows
#'   \item Applies \code{rout_outliers()} to dose rows only
#'   \item Reinserts control rows into their original positions
#'   \item Replaces detected outliers with NA
#'   \item Stores cleaned and (optionally) original tables
#' }
#'
#' @param batch_results A named list of plate results. Each element must contain
#' a \code{modified_ratio_table}, typically generated by
#' \code{batch_ratio_analysis()}.
#'
#' @param Q Numeric. False discovery rate threshold for ROUT outlier detection.
#' Must be strictly between 0 and 1 (default = 0.01).
#'
#' @param n_param Integer. Number of parameters for the Hill model:
#' \itemize{
#'   \item 3: 3-parameter logistic model
#'   \item 4: 4-parameter logistic model
#' }
#'
#' @param direction Character. Curve direction:
#' \itemize{
#'   \item "inhibition" (default)
#'   \item "agonist"
#' }
#'
#' @param min_dynamic_range Numeric. Minimum dynamic range (\%) required for
#' curve evaluation (default = 20).
#'
#' @param ntry_retry Integer. Number of retry attempts for model fitting if
#' convergence fails.
#'
#' @param keep_cytotoxic Logical.  When \code{TRUE} (default \code{FALSE}),
#'   ROUT-flagged outliers that are consistent with cytotoxicity are
#'   \emph{rescued} (restored to their original values and removed from the
#'   outlier list).  A point is rescued only when \strong{both} of the
#'   following conditions are met simultaneously:
#'   \enumerate{
#'     \item \strong{Replicate agreement}: \emph{both} replicates at that
#'       concentration are flagged by ROUT (i.e. the drop is reproducible,
#'       not a single-replicate artefact).
#'     \item \strong{Top-2 concentration}: the flagged concentration is one
#'       of the two highest tested concentrations in the plate.
#'   }
#'   Rescued points are logged in \code{$rescued_summary} for full
#'   traceability.  Set to \code{FALSE} (default) for NanoBRET data, where
#'   high-concentration drops are more likely to be technical artefacts
#'   (compound fluorescence, precipitation) than true biology.
#'
#' @param verbose Logical. If TRUE, prints progress and summary messages.
#'
#' @return A list containing:
#' \itemize{
#'   \item Updated plate entries with cleaned \code{modified_ratio_table}
#'   \item Optional \code{modified_ratio_table_original} when outliers are detected
#'   \item \code{outlier_summary}: aggregated outliers across all plates
#'   \item \code{skipped_summary}: skipped compounds and reasons
#'   \item \code{params}: parameters used in the analysis
#' }
#'
#' The returned object is invisible (assign it to a variable to use it).
#'
#' @section Column Filtering:
#' Columns are automatically removed if:
#' \itemize{
#'   \item Their name starts with "NA"
#'   \item More than 80\% of their values are NA or NaN
#' }
#'
#' Removed columns are reported in \code{skipped_summary}.
#'
#' @section Control Rows:
#' Rows where the concentration column is NA are treated as controls:
#' \itemize{
#'   \item Excluded from model fitting
#'   \item Reinserted into the cleaned table at their original positions
#' }
#'
#' This preserves compatibility with downstream normalization and plotting.
#'
#' @section Outlier Handling:
#' \itemize{
#'   \item Outliers are detected using \code{rout_outliers()}
#'   \item Flagged values are replaced with NA in the cleaned table
#'   \item Original values are stored in the attribute
#'   \code{attr(modified_ratio_table, "outliers_replaced")}
#' }
#'
#' @section Skipped Compounds:
#' Compounds may be skipped due to:
#' \itemize{
#'   \item Empty or NA-only columns
#'   \item Insufficient valid data points
#'   \item Model fitting failure
#' }
#'
#' These are recorded in \code{skipped_summary}.
#'
#' @section Important Notes:
#' \itemize{
#'   \item The function assumes log10-transformed concentrations.
#'   \item Safe to re-run: previous outputs are overwritten cleanly.
#'   \item Designed for integration with batch pipelines and downstream analysis.
#' }
#'
#' @examples
#' \dontrun{
#' batch_clean <- rout_outliers_batch(
#'   batch_results = my_batch,
#'   Q = 0.01,
#'   n_param = 4,
#'   direction = "inhibition"
#' )
#'
#' # Access summary of all outliers
#' batch_clean$outlier_summary
#'
#' # Access cleaned table for a specific plate
#' batch_clean$Plate1$result$modified_ratio_table
#' }
#'
#' @seealso
#' \code{rout_outliers}, \code{ratio_dose_response_v2}
#'
#' @export

rout_outliers_batch <- function(batch_results,
                                Q                 = 0.01,
                                n_param           = 4L,
                                direction         = "inhibition",
                                min_dynamic_range = 20,
                                ntry_retry        = 3L,
                                keep_cytotoxic    = FALSE,
                                verbose           = TRUE) {

  # --------------------------------------------------------------------------
  # 1. Input validation
  # --------------------------------------------------------------------------
  if (!is.list(batch_results) || length(batch_results) == 0L)
    stop("batch_results must be a non-empty named list of plate results.")

  if (!n_param %in% c(3L, 4L))
    stop("n_param must be 3 or 4.")

  if (!direction %in% c("inhibition", "agonist"))
    stop('direction must be "inhibition" or "agonist".')

  if (!is.numeric(Q) || length(Q) != 1L || Q <= 0 || Q >= 1)
    stop("Q must be a single number strictly between 0 and 1.")

  if (!is.numeric(ntry_retry) || length(ntry_retry) != 1L || ntry_retry < 0)
    stop("ntry_retry must be a single non-negative integer.")
  ntry_retry <- as.integer(ntry_retry)

  if (!is.logical(keep_cytotoxic) || length(keep_cytotoxic) != 1L)
    stop("keep_cytotoxic must be a single logical value (TRUE or FALSE).")

  # Verify rout_outliers is available
  if (!exists("rout_outliers", mode = "function"))
    stop(paste0(
      "rout_outliers() not found. ",
      "Please source('rout_outliers.R') before calling this function."))

  # --------------------------------------------------------------------------
  # 2. Helpers
  # --------------------------------------------------------------------------

  # Detect and remove NA/empty columns from a modified_ratio_table.
  # Returns list(clean_table, skipped_cols) where skipped_cols is a character
  # vector of column names that were removed.
  .remove_na_columns <- function(tbl) {
    value_cols <- seq(2L, ncol(tbl))          # col 1 is concentration
    col_names  <- colnames(tbl)[value_cols]

    # A column is "NA/empty" if:
    #   (a) its name starts with "NA" (e.g. "NA:NA", "NA_2:NA"), OR
    #   (b) > 80% of its values are NA or NaN
    is_na_col <- vapply(value_cols, function(j) {
      nm  <- colnames(tbl)[j]
      # Check name: compound part is before the first ":"
      cmpd_part <- strsplit(nm, ":")[[1L]][1L]
      if (grepl("^NA", cmpd_part)) return(TRUE)
      vals <- tbl[[j]]
      # BUG_4 fix: is.nan() is only valid on numeric vectors; guard before calling
      # it to avoid spurious warnings on character columns.
      na_frac <- if (is.numeric(vals)) mean(is.na(vals) | is.nan(vals))
      else                  mean(is.na(vals))
      na_frac > 0.8
    }, logical(1L))

    # Pair-aware removal: data columns come in replicate pairs (col i, col i+1).
    # If either column of a pair is flagged, remove BOTH -- otherwise the
    # remaining orphan column makes the total data-column count odd, which
    # causes fit_drc_3pl() to stop with "Number of response columns must be even".
    n_data <- length(is_na_col)
    if (n_data >= 2L) {
      pair_starts <- seq(1L, n_data - 1L, by = 2L)   # indices within is_na_col
      for (p in pair_starts) {
        if (is_na_col[p] || is_na_col[p + 1L]) {
          is_na_col[p]       <- TRUE
          is_na_col[p + 1L]  <- TRUE
        }
      }
    }

    skipped <- col_names[is_na_col]
    clean   <- tbl[, c(1L, value_cols[!is_na_col]), drop = FALSE]
    list(clean_table = clean, skipped_cols = skipped)
  }

  # Prepend a plate column to a data.frame (used for summary tables).
  .prepend_plate <- function(df, plate_name) {
    if (nrow(df) == 0L) {
      df$plate <- character(0L)
      return(df[, c("plate", setdiff(names(df), "plate")), drop = FALSE])
    }
    cbind(data.frame(plate = plate_name, stringsAsFactors = FALSE), df)
  }

  # Cytotoxicity rescue filter.
  # Takes the outlier_table and cleaned_mrt from a single plate and restores
  # points that are consistent with cytotoxicity rather than technical error.
  #
  # A point is rescued when BOTH replicates at the same compound + concentration
  # are flagged (reproducible drop). The top-2 concentration rank is used as
  # an informational label in the rescue_reason column but is NOT a hard gate —
  # reproducible same-concentration flags anywhere in the dose range can reflect
  # real biology (e.g. cytotoxicity at sub-maximal concentrations).
  #
  # Returns list(cleaned_mrt, outlier_table, rescued_rows) where rescued_rows
  # is a data.frame (subset of outlier_table) of the rescued entries.
  .rescue_cytotoxic <- function(outlier_tbl, cleaned_mrt, original_mrt) {

    if (nrow(outlier_tbl) == 0L)
      return(list(cleaned_mrt  = cleaned_mrt,
                  outlier_tbl  = outlier_tbl,
                  rescued_rows = outlier_tbl[0L, ]))

    # Concentration column name (log10_conc or ln_conc)
    conc_col_name <- intersect(c("log10_conc", "ln_conc"), names(outlier_tbl))[1L]

    # Top-2 concentrations (used for labelling only, not as a hard filter)
    conc_col_idx <- 1L
    all_concs    <- sort(unique(stats::na.omit(cleaned_mrt[[conc_col_idx]])),
                         decreasing = TRUE)
    top2_concs   <- all_concs[seq_len(min(2L, length(all_concs)))]

    rescue_mask   <- logical(nrow(outlier_tbl))
    rescue_reason <- character(nrow(outlier_tbl))

    for (i in seq_len(nrow(outlier_tbl))) {
      conc_i <- outlier_tbl[[conc_col_name]][i]
      cmpd_i <- outlier_tbl$compound[i]

      # Condition: both replicates at this compound + concentration are flagged
      same_cmpd_conc <- outlier_tbl$compound == cmpd_i &
        outlier_tbl[[conc_col_name]] == conc_i
      if (sum(same_cmpd_conc) < 2L) next

      rescue_mask[i]   <- TRUE
      rescue_reason[i] <- if (conc_i %in% top2_concs)
        "both replicates flagged at top-2 concentration (cytotoxicity)"
      else
        "both replicates flagged at same concentration (reproducible drop)"
    }

    if (!any(rescue_mask))
      return(list(cleaned_mrt  = cleaned_mrt,
                  outlier_tbl  = outlier_tbl,
                  rescued_rows = outlier_tbl[0L, ]))

    rescued_rows <- outlier_tbl[rescue_mask, , drop = FALSE]
    rescued_rows$rescue_reason <- rescue_reason[rescue_mask]

    # Restore original values in cleaned_mrt for rescued rows
    restored_mrt <- cleaned_mrt
    for (i in seq_len(nrow(rescued_rows))) {
      r   <- rescued_rows$row[i]
      col <- rescued_rows$column[i]
      if (col %in% colnames(original_mrt) && r >= 1L && r <= nrow(original_mrt))
        restored_mrt[r, col] <- original_mrt[r, col]
    }

    list(cleaned_mrt  = restored_mrt,
         outlier_tbl  = outlier_tbl[!rescue_mask, , drop = FALSE],
         rescued_rows = rescued_rows)
  }

  # --------------------------------------------------------------------------
  # 3. Identify plate names
  # Exclude reserved elements appended by this function itself so that
  # re-running on already-processed output is safe.
  # --------------------------------------------------------------------------
  reserved <- c("outlier_summary", "skipped_summary", "rescued_summary", "params")
  plate_names <- setdiff(names(batch_results), reserved)

  if (length(plate_names) == 0L)
    stop("No plate entries found in batch_results (all names are reserved).")

  if (verbose) {
    cat(strrep("=", 60), "\n")
    cat("NANOBRET BATCH ROUT OUTLIER DETECTION\n")
    cat(strrep("=", 60), "\n")
    cat(sprintf("Plates           : %d\n", length(plate_names)))
    cat(sprintf("ROUT Q           : %.3f\n", Q))
    cat(sprintf("Model            : %s\n",
                if (n_param == 4L) "4PL (Hill free)" else "3PL (Hill fixed)"))
    cat(sprintf("Direction        : %s\n", direction))
    cat(sprintf("ntry_retry       : %d\n", ntry_retry))
    cat(sprintf("keep_cytotoxic   : %s\n\n", keep_cytotoxic))
  }

  # --------------------------------------------------------------------------
  # 4. Per-plate processing
  # --------------------------------------------------------------------------
  outlier_list <- list()
  skipped_list <- list()
  rescued_list <- list()
  output       <- batch_results   # start with a full copy; patch in place

  for (plate_name in plate_names) {

    plate <- batch_results[[plate_name]]

    if (verbose) cat(sprintf("--- %s ---\n", plate_name))

    # BUG_2 fix: clear any stale _original table from a previous run so that
    # re-running on the same output object does not carry forward stale data.
    output[[plate_name]]$result$modified_ratio_table_original <- NULL

    # ---- 4a. Locate modified_ratio_table ----
    mrt <- tryCatch(plate$result$modified_ratio_table, error = function(e) NULL)

    if (is.null(mrt) || !is.data.frame(mrt) || nrow(mrt) == 0L || ncol(mrt) < 3L) {
      if (verbose)
        message(sprintf("  Skipping %s: modified_ratio_table not found or too small.",
                        plate_name))
      next
    }

    # ---- 4b. Remove NA/empty columns silently ----
    cleaned_cols <- .remove_na_columns(mrt)
    mrt_clean    <- cleaned_cols$clean_table
    skipped_cols <- cleaned_cols$skipped_cols

    if (length(skipped_cols) > 0L) {
      sk <- data.frame(
        compound          = skipped_cols,
        reason            = "NA/empty column",
        n_valid           = 0L,
        dynamic_range_pct = NA_real_,
        stringsAsFactors  = FALSE)
      # BUG_6 fix: use a source-specific key so ROUT-level skips (written below)
      # do not overwrite NA-column skips for the same plate.
      skipped_list[[paste0(plate_name, "__na")]] <- .prepend_plate(sk, plate_name)
    }

    if (ncol(mrt_clean) < 3L) {
      if (verbose)
        message(sprintf("  Skipping %s: no valid compound columns remain after NA removal.",
                        plate_name))
      next
    }

    # ---- 4c. Separate control rows (NA concentration) from dose rows ----
    # modified_ratio_table can have multiple NA-concentration rows:
    #   - Row at the top:    0% control mean (e.g. original row 24)
    #   - Row at the bottom: 100% control mean (e.g. original row 12)
    # Both must be excluded from ROUT fitting and re-inserted at their
    # ORIGINAL positions in the cleaned output. Inserting them all at the
    # top (as the previous single-row logic did) breaks normalize=TRUE in
    # batch_drc_analysis() because it expects the 100% control at the bottom.
    conc_col1    <- mrt_clean[[1L]]
    ctrl_rows    <- which(is.na(conc_col1))   # all NA-concentration rows
    dose_rows    <- which(!is.na(conc_col1))  # all real dose rows

    if (length(dose_rows) < 2L) {
      if (verbose)
        message(sprintf("  Skipping %s: fewer than 2 dose rows after control removal.",
                        plate_name))
      next
    }

    has_ctrl_rows <- length(ctrl_rows) > 0L

    if (has_ctrl_rows) {
      # Extract only the dose rows for fitting; reset row names to 1-based
      # so that rout_outliers() internal indices are 1-based within
      # tbl_for_fit. This is required for the row-index adjustment in 4e/4g.
      tbl_for_fit           <- mrt_clean[dose_rows, , drop = FALSE]
      rownames(tbl_for_fit) <- NULL
    } else {
      tbl_for_fit <- mrt_clean
    }

    # ---- 4d. Run ROUT outlier detection ----
    rout_out <- tryCatch(
      rout_outliers(
        data              = tbl_for_fit,
        Q                 = Q,
        n_param           = n_param,
        conc_col          = 1L,
        log_base          = "log10",
        direction         = direction,
        min_dynamic_range = min_dynamic_range,
        ntry_retry        = ntry_retry,
        verbose           = verbose
      ),
      error = function(e) {
        warning(sprintf("rout_outliers() failed for plate '%s': %s",
                        plate_name, e$message))
        NULL
      }
    )

    if (is.null(rout_out)) next

    # ---- 4e. Reconstruct the full modified_ratio_table ----
    # rout_out$cleaned_table covers only the dose rows (control rows were
    # excluded before fitting). Re-insert all control rows at their ORIGINAL
    # positions so the output table has the same row order as the input.
    #
    # Strategy: build a full-length skeleton from mrt_clean, fill dose
    # positions with the cleaned values, leave control positions unchanged.
    cleaned_mrt <- rout_out$cleaned_table   # dose rows only, 1-based

    if (has_ctrl_rows) {
      # Allocate a full table (same dimensions as mrt_clean)
      full_mrt <- mrt_clean   # start with original (controls already correct)
      # Overwrite dose positions with the ROUT-cleaned values
      full_mrt[dose_rows, ] <- cleaned_mrt
      rownames(full_mrt)    <- NULL
      cleaned_mrt           <- full_mrt
    }

    # Carry the outliers_replaced attribute from the inner call.
    # Row indices in the attribute refer to tbl_for_fit (dose rows only,
    # 1-based). Map them back to the original mrt_clean row numbers using
    # the dose_rows index vector: tbl_for_fit row i -> mrt_clean row dose_rows[i].
    or_attr <- attr(rout_out$cleaned_table, "outliers_replaced")
    if (!is.null(or_attr) && nrow(or_attr) > 0L && has_ctrl_rows) {
      or_attr$row <- dose_rows[or_attr$row]
    }
    attr(cleaned_mrt, "outliers_replaced") <- or_attr

    # ---- 4f. Map outlier row indices back to mrt_clean row numbers ----
    # rout_out$outlier_table rows refer to tbl_for_fit (dose rows only,
    # 1-based). Map them back to mrt_clean row numbers before rescue/storage.
    plate_outlier_tbl <- rout_out$outlier_table
    if (nrow(plate_outlier_tbl) > 0L && has_ctrl_rows)
      plate_outlier_tbl$row <- dose_rows[plate_outlier_tbl$row]

    # ---- 4g. Cytotoxicity rescue (only when keep_cytotoxic = TRUE) ----
    # Restores flagged points that meet BOTH criteria:
    #   (1) Both replicates at that compound+concentration are flagged.
    #   (2) The concentration is one of the top 2 tested concentrations.
    # Rescued points are removed from plate_outlier_tbl and logged separately.
    rescued_rows_plate <- plate_outlier_tbl[0L, ]   # empty placeholder

    if (keep_cytotoxic && nrow(plate_outlier_tbl) > 0L) {
      rescue_out <- .rescue_cytotoxic(
        outlier_tbl  = plate_outlier_tbl,
        cleaned_mrt  = cleaned_mrt,
        original_mrt = mrt_clean
      )
      cleaned_mrt        <- rescue_out$cleaned_mrt
      plate_outlier_tbl  <- rescue_out$outlier_tbl
      rescued_rows_plate <- rescue_out$rescued_rows

      if (nrow(rescued_rows_plate) > 0L) {
        if (verbose)
          message(sprintf(
            "  keep_cytotoxic: rescued %d point(s) for: %s",
            nrow(rescued_rows_plate),
            paste(unique(rescued_rows_plate$compound), collapse = ", ")))

        # Update the outliers_replaced attribute to reflect the rescue
        or_attr_updated <- attr(cleaned_mrt, "outliers_replaced")
        if (!is.null(or_attr_updated) && nrow(or_attr_updated) > 0L) {
          rescued_cols <- rescued_rows_plate$column
          rescued_rows_idx <- rescued_rows_plate$row
          keep_mask <- !(or_attr_updated$column %in% rescued_cols &
                           or_attr_updated$row    %in% rescued_rows_idx)
          attr(cleaned_mrt, "outliers_replaced") <- or_attr_updated[keep_mask, , drop = FALSE]
        }
      }
    }

    # ---- 4h. Patch the plate in the output list ----
    # Store the pre-cleaning table when outliers were removed OR when points
    # were rescued. The plot function needs the original values to re-fit on;
    # if all outliers were rescued (plate_outlier_tbl is empty) but rescued
    # points exist, the original must still be stored so the plot can re-fit
    # on the full data and then suppress the rescued points' X markers.
    if (nrow(plate_outlier_tbl) > 0L || nrow(rescued_rows_plate) > 0L) {
      output[[plate_name]]$result$modified_ratio_table_original <- mrt_clean
    }
    output[[plate_name]]$result$modified_ratio_table <- cleaned_mrt

    # Store per-plate rescued points so plot_outliers_batch_curves() can
    # suppress the red-X marker for these compound+concentration pairs.
    # Always written (empty data frame when nothing was rescued) so the
    # plot function can rely on it being present without NULL checks.
    output[[plate_name]]$result$rescued_cytotoxic <- rescued_rows_plate

    # Store the ROUT results (with rescue flags already cleared) so the plot
    # function can use them directly instead of re-running ROUT from scratch.
    # This prevents any discrepancy between what was detected/rescued during
    # the batch run and what the plot shows.
    #
    # Apply rescue flag-clearing to rout_out$results now, before storing.
    if (nrow(rescued_rows_plate) > 0L) {
      conc_col_name_r <- intersect(c("log10_conc", "ln_conc"),
                                   names(rout_out$results))[1L]
      for (.i in seq_len(nrow(rescued_rows_plate))) {
        .cmpd <- rescued_rows_plate$compound[.i]
        .conc <- rescued_rows_plate[[conc_col_name_r]][.i]
        .mask <- rout_out$results$compound == .cmpd &
          abs(rout_out$results[[conc_col_name_r]] - .conc) < 1e-9
        rout_out$results$outlier_fdr[.mask] <- FALSE
        rout_out$results$outlier_raw[.mask] <- FALSE
      }
    }
    # Map row indices in rout_out$results back from tbl_for_fit (1-based dose
    # rows) to mrt_clean row numbers, so the stored results are self-consistent
    # with the row numbers in outlier_summary and modified_ratio_table.
    # (rout_out$results does not carry row indices directly, but the params
    # and curve data are unaffected by this mapping.)
    output[[plate_name]]$result$rout_results <- rout_out

    # ---- 4i. Collect per-plate summaries ----
    if (nrow(plate_outlier_tbl) > 0L)
      outlier_list[[plate_name]] <- .prepend_plate(plate_outlier_tbl, plate_name)

    if (nrow(rescued_rows_plate) > 0L)
      rescued_list[[plate_name]] <- .prepend_plate(rescued_rows_plate, plate_name)

    if (nrow(rout_out$skipped_table) > 0L) {
      # BUG_6 fix: use a source-specific key so this does not overwrite the
      # NA-column skip entry written above for the same plate.
      skipped_list[[paste0(plate_name, "__rout")]] <- .prepend_plate(rout_out$skipped_table, plate_name)
    }

    if (verbose) {
      n_out     <- nrow(plate_outlier_tbl)
      n_rescued <- nrow(rescued_rows_plate)
      n_skip    <- nrow(rout_out$skipped_table)
      if (keep_cytotoxic && n_rescued > 0L) {
        cat(sprintf("  -> %d outlier(s) detected, %d rescued (cytotoxic), %d compound(s) skipped\n\n",
                    n_out + n_rescued, n_rescued, n_skip))
      } else {
        cat(sprintf("  -> %d outlier(s) detected, %d compound(s) skipped\n\n",
                    n_out, n_skip))
      }
    }
  }

  # --------------------------------------------------------------------------
  # 5. Aggregate summaries
  # --------------------------------------------------------------------------
  outlier_summary <- if (length(outlier_list) > 0L) {
    do.call(rbind, outlier_list)
  } else {
    data.frame(plate = character(), compound = character(), column = character(),
               replicate = integer(), row = integer(), log10_conc = numeric(),
               bret_ratio = numeric(), fitted = numeric(),
               std_residual = numeric(), dynamic_range_pct = numeric(),
               stringsAsFactors = FALSE)
  }

  skipped_summary <- if (length(skipped_list) > 0L) {
    do.call(rbind, skipped_list)
  } else {
    data.frame(plate = character(), compound = character(), reason = character(),
               n_valid = integer(), dynamic_range_pct = numeric(),
               stringsAsFactors = FALSE)
  }

  rescued_summary <- if (length(rescued_list) > 0L) {
    do.call(rbind, rescued_list)
  } else {
    data.frame(plate = character(), compound = character(), column = character(),
               replicate = integer(), row = integer(), log10_conc = numeric(),
               bret_ratio = numeric(), fitted = numeric(),
               std_residual = numeric(), dynamic_range_pct = numeric(),
               rescue_reason = character(),
               stringsAsFactors = FALSE)
  }

  rownames(outlier_summary) <- NULL
  rownames(skipped_summary) <- NULL
  rownames(rescued_summary) <- NULL

  # --------------------------------------------------------------------------
  # 6. Verbose final summary
  # --------------------------------------------------------------------------
  if (verbose) {
    cat(strrep("=", 60), "\n")
    cat("BATCH OUTLIER DETECTION COMPLETE\n")
    cat(strrep("=", 60), "\n")
    cat(sprintf("Plates processed : %d / %d\n",
                length(plate_names) - sum(!plate_names %in% names(output)),
                length(plate_names)))
    cat(sprintf("Total outliers   : %d\n", nrow(outlier_summary)))
    if (keep_cytotoxic)
      cat(sprintf("Total rescued    : %d (cytotoxic, kept)\n", nrow(rescued_summary)))
    cat(sprintf("Total skipped    : %d compound(s)\n\n", nrow(skipped_summary)))

    if (nrow(outlier_summary) > 0L) {
      cat("Outlier summary:\n")
      show_cols <- intersect(
        c("plate", "compound", "log10_conc", "bret_ratio", "std_residual"),
        names(outlier_summary))
      print(outlier_summary[, show_cols, drop = FALSE],
            row.names = FALSE, digits = 3)
      cat("\n")
    }

    if (keep_cytotoxic && nrow(rescued_summary) > 0L) {
      cat("Rescued (cytotoxic) summary:\n")
      show_cols_r <- intersect(
        c("plate", "compound", "log10_conc", "bret_ratio", "rescue_reason"),
        names(rescued_summary))
      print(rescued_summary[, show_cols_r, drop = FALSE],
            row.names = FALSE, digits = 3)
      cat("\n")
    }
  }

  # --------------------------------------------------------------------------
  # 7. Append summary elements and return
  # --------------------------------------------------------------------------
  output$outlier_summary <- outlier_summary
  output$skipped_summary <- skipped_summary
  output$rescued_summary <- rescued_summary
  output$params <- list(
    Q                 = Q,
    n_param           = n_param,
    direction         = direction,
    log_base          = "log10",   # hardcoded  --  modified_ratio_table is always log10
    ntry_retry        = ntry_retry,
    keep_cytotoxic    = keep_cytotoxic
  )

  return(invisible(output))
}
