#' Generate a formatted Scarab table from experimental data
#'
#' This function creates a comprehensive summary table in the Scarab format,
#' combining data from raw results and dose-response curve fitting. The table
#' includes experimental metadata, quality control metrics, curve parameters,
#' and raw BRET values for each compound.
#'
#' @param results_list List containing raw experimental results from multiple plates,
#'   typically generated by the \code{\link{batch_ratio_analysis}} function.
#'   Must contain plate-specific data with modified ratio tables and quality metrics.
#' @param drc_results_list List containing dose-response curve fitting results,
#'   typically generated by the \code{\link{batch_drc_analysis}} function.
#'   Must contain final summary tables for each plate.
#' @param plate_name Character string specifying which plate to process.
#'   Should match a plate name in both results_list and drc_results_list
#'   (e.g., "plate_01", "plate_02"). Default is "plate_01".
#' @param date Character string with experiment date in format "YYMMDD".
#'   Used to construct Experiment IDs. Default is "260303".
#' @param experimenter_abbrev Character string with experimenter initials.
#'   Used to construct Experiment IDs. Default is "JD".
#' @param sgc_global_compound_id Character string or NA with SGC global compound identifier/batch number.
#'   This value will be applied to all compounds in the plate. Default is NA.
#' @param tracer_kd_app Numeric or NA with tracer KD app value as log.
#'   Default is NA.
#' @param tracer_concentration_used Numeric or NA with tracer concentration used as log.
#'   Default is NA.
#' @param nLuc_orientation Orientation of nLuc. Can be specified in three ways:
#'   \itemize{
#'     \item \strong{Single character}: "C" or "N" - applies the same orientation to all kinases
#'     \item \strong{Named vector}: e.g., \code{c(LRRK2 = "C", AAK1 = "N")} - specifies orientation for specific kinases
#'     \item \strong{Unnamed vector}: e.g., \code{c("C", "N", "C")} - applies orientations in the order of unique kinases appearing in the plate
#'   }
#'   Kinases without specified orientation default to "C" (with a warning).
#'   Default is "C".
#' @param experiment_type Character string describing experiment type.
#'   Default is "intact mode".
#' @param cell_line Character string with cell line used.
#'   Default is "HEK293T".
#' @param transfection_mode Character string with transfection method.
#'   Default is "Flask Transfection".
#' @param tracer Character string with tracer name.
#'   Default is "Tracer K10".
#' @param tracer_comment Character string with tracer comments.
#'   Default is "at Tracer KDapp".
#' @param assay_volume Character string with assay volume in µL.
#'   Default is "10".
#' @param plate_format Character string with plate format.
#'   Default is "384-well".
#' @param plate_manufacturer Character string with plate manufacturer/catalog number.
#'   Default is "784075".
#' @param plate_material Character string with plate material.
#'   Default is "PS" (polystyrene).
#' @param eln_id Character string or NA with Electronic Lab Notebook ID.
#'   Default is NA.
#' @param comments Character string or NA with additional comments.
#'   Default is NA.
#' @param date_created Character string with creation date and time.
#'   Default is current time in format "YYYY-MM-DD HH:MM:SS".
#' @param record_creator Character string with name of person creating the record.
#'   Default is system username.
#' @param fit_used Character string describing the fitting model used.
#'   Default is "log(inhibitor) vs. response (three parameters)".
#' @param save Logical indicating whether to save the table as Excel file.
#'   Default is TRUE.
#' @param file_name Character string or NULL for custom file name.
#'   If NULL, generates "scarab_table_plate_name.xlsx" (e.g., "scarab_table_plate_01.xlsx").
#'   Default is NULL.
#' @param decimal_separator Character specifying decimal separator for numeric values.
#'   Must be either "." (dot) or "," (comma). Useful for different regional Excel settings.
#'   Default is ".".
#'
#' @return A data frame with 77 rows and multiple columns (one per unique compound).
#'   The first column "Field" contains the parameter names, and subsequent columns
#'   (X4, X5, ...) contain data for each compound. The number of compound columns
#'   depends on how many unique compounds are present in the plate.
#'
#' @details
#' This function is designed to work seamlessly with the output of two other functions
#' in this package:
#' \itemize{
#'   \item \code{\link{batch_ratio_analysis}}: Generates the \code{results_list} with raw data
#'   \item \code{\link{batch_drc_analysis}}: Generates the \code{drc_results_list} with curve fitting results
#' }
#'
#' The function generates a comprehensive table with the following sections:
#'
#' \strong{Basic Information (Rows 1-10):}
#' \itemize{
#'   \item \code{Kinase}: Extracted from column names (e.g., "LRRK2" from "LRRK2:MDKM34")
#'   \item \code{nLuc Orientation}: Specified via \code{nLuc_orientation} parameter
#'   \item \code{Compound}: Compound name (e.g., "MDKM34")
#'   \item \code{Experiment ID}: Generated as \code{date-experimenter_abbrev-Kinase-Compound}
#'   \item \code{Construct ID}: Auto-generated as \code{{Kinase}A-nb001} (for N) or \code{{Kinase}A-nb002} (for C)
#' }
#'
#' \strong{Curve Parameters (Rows 11-18):}
#' Extracted from \code{final_summary_table} in \code{drc_results_list}
#' \itemize{
#'   \item LogIC50, IC50, HillSlope, R², etc.
#' }
#'
#' \strong{Quality Control (Rows 19-29):}
#' Extracted from \code{interval_means} in \code{results_list}
#' \itemize{
#'   \item Controls (Positive, Background), Z', Assay window, etc.
#' }
#'
#' \strong{Experimental Details (Rows 30-37):}
#' \itemize{
#'   \item Tracer information, plate specifications, etc.
#' }
#'
#' \strong{Concentration Data (Rows 38-73):}
#' \itemize{
#'   \item \code{LOG Compound Concentration 1-12}: From \code{modified_ratio_table}
#'   \item \code{Compound Concentration X BRET}: From main columns (without .2 suffix)
#'   \item \code{Compound Concentration X BRET-Duplicate}: From duplicate columns (with .2 suffix)
#' }
#'
#' \strong{Metadata (Rows 74-77):}
#' \itemize{
#'   \item ELN ID, Comments, Date Created, Record Creator
#' }
#'
#' The Construct ID (row 7) is automatically generated based on kinase and orientation:
#' \itemize{
#'   \item If orientation is \code{"N"}: \code{{kinase}A-nb001}
#'   \item If orientation is \code{"C"}: \code{{kinase}A-nb002}
#' }
#'
#' All numeric values are converted to character strings to maintain formatting
#' and allow mixed content in columns. The \code{decimal_separator} parameter
#' controls whether numbers use "." (e.g., "3.14") or "," (e.g., "3,14").
#'
#' @seealso
#' \code{\link{batch_ratio_analysis}} for generating the input results_list,
#' \code{\link{batch_drc_analysis}} for generating the input drc_results_list.
#'
#' @examples
#' \dontrun{
#' # First, run the analysis functions to get the required lists
#' results <- batch_ratio_analysis("path/to/data")
#' drc_results <- batch_drc_analysis(results)
#'
#' # Basic usage with default values
#' table1 <- scarab_table(results, drc_results, plate_name = "plate_01")
#'
#' # Customize experimental parameters
#' table2 <- scarab_table(
#'   results,
#'   drc_results,
#'   plate_name = "plate_02",
#'   date = "240101",
#'   experimenter_abbrev = "MT",
#'   sgc_global_compound_id = "K0000697e",
#'   cell_line = "HEK293"
#' )
#'
#' # Specify different orientations for different kinases
#'
#' ## Option 1: Single string (all kinases same)
#' table3 <- scarab_table(results, drc_results, nLuc_orientation = "N")
#'
#' ## Option 2: Named vector (specific per kinase)
#' table4 <- scarab_table(
#'   results,
#'   drc_results,
#'   nLuc_orientation = c(LRRK2 = "C", AAK1 = "N")
#' )
#'
#' ## Option 3: Unnamed vector (in order of unique kinases)
#' ## If unique kinases are: LRRK2, AAK1, OTHER
#' table5 <- scarab_table(
#'   results,
#'   drc_results,
#'   nLuc_orientation = c("C", "N", "C")
#' )
#'
#' # Use comma as decimal separator (for European format)
#' table6 <- scarab_table(
#'   results,
#'   drc_results,
#'   decimal_separator = ","
#' )
#'
#' # Save with custom filename
#' table7 <- scarab_table(
#'   results,
#'   drc_results,
#'   save = TRUE,
#'   file_name = "my_experiment_results"
#' )
#'
#' # Return table without saving
#' table8 <- scarab_table(results, drc_results, save = FALSE)
#' }
#'
#' @importFrom openxlsx write.xlsx
#' @export

scarab_table <- function(results_list, drc_results_list,
                         plate_name = "plate_01",
                         date = "260303",
                         experimenter_abbrev = "JD",
                         sgc_compound_id = NA,
                         tracer_kd_app = NA,
                         tracer_concentration_used = NA,
                         nLuc_orientation = "C",
                         experiment_type = "intact mode",
                         cell_line = "HEK293T",
                         transfection_mode = "Flask Transfection",
                         tracer = "Tracer K10",
                         tracer_comment = "at Tracer KDapp",
                         assay_volume = "10",
                         plate_format = "384-well",
                         plate_manufacturer = "784075",
                         plate_material = "PS",
                         eln_id = NA,
                         comments = NA,
                         date_created = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
                         record_creator = Sys.info()["user"],
                         fit_used = "log(inhibitor) vs. response (three parameters)",
                         save = TRUE,
                         file_name = NULL,
                         decimal_separator = ".") {

  # Validate decimal separator
  if(!decimal_separator %in% c(".", ",")) {
    stop("decimal_separator must be either '.' or ','")
  }

  # Helper function to format numbers with correct decimal separator
  format_number <- function(x, digits = NULL) {
    # Handle NULL or NA
    if(is.null(x)) return(NA_character_)

    # Apply to each element if it's a vector
    if(length(x) > 1) {
      return(sapply(x, function(val) format_number(val, digits)))
    }

    # Single value processing
    if(is.na(x) || is.null(x) || x == "<NA>" || x == "NA") {
      return(NA_character_)
    }

    # Try to convert to numeric
    x_num <- suppressWarnings(as.numeric(x))
    if(is.na(x_num)) {
      return(as.character(x))  # Return as is if not numeric
    }

    if(decimal_separator == ".") {
      if(!is.null(digits)) {
        return(as.character(round(x_num, digits)))
      } else {
        return(as.character(x_num))
      }
    } else {
      # Replace "." with "," for decimal separator
      if(!is.null(digits)) {
        num_str <- format(round(x_num, digits), nsmall = digits)
      } else {
        num_str <- as.character(x_num)
      }
      return(gsub("\\.", ",", num_str))
    }
  }

  # Helper function to get orientation for a specific kinase
  get_orientation <- function(kinase, orientation_arg, unique_kinases_list) {

    # Case 1: orientation_arg is a single string
    if(is.character(orientation_arg) && length(orientation_arg) == 1) {
      if(!orientation_arg %in% c("C", "N")) {
        stop("Single string orientation must be either 'C' or 'N'")
      }
      return(orientation_arg)
    }

    # Case 2: orientation_arg is a named vector
    if(!is.null(names(orientation_arg))) {
      if(kinase %in% names(orientation_arg)) {
        return(orientation_arg[kinase])
      } else {
        warning(paste("Kinase", kinase, "not found in named vector. Using default 'C'"))
        return("C")
      }
    }

    # Case 3: orientation_arg is an unnamed vector - match by order
    if(is.vector(orientation_arg) && is.character(orientation_arg)) {
      kinase_index <- which(unique_kinases_list == kinase)
      if(kinase_index <= length(orientation_arg)) {
        return(orientation_arg[kinase_index])
      } else {
        warning(paste("No orientation specified for kinase", kinase, "at position", kinase_index,
                      ". Using default 'C'"))
        return("C")
      }
    }

    # Default case
    warning("Orientation format not recognized. Using 'C'")
    return("C")
  }

  # Access specific plate
  plate_results <- results_list[[plate_name]]
  plate_drc <- drc_results_list$drc_results[[plate_name]]

  # Check if plate exists
  if(is.null(plate_results)) {
    stop(paste("Plate", plate_name, "not found in results_list"))
  }

  # Extract data tables
  modified_table <- plate_results$result$modified_ratio_table
  quality_table <- plate_results$result$interval_means
  final_summary <- plate_drc$drc_result$final_summary_table

  # Identify compound columns (excluding log(inhibitor).[M])
  compound_cols <- names(modified_table)[!names(modified_table) %in% c("log(inhibitor).[M]", "NA:NA", "NA:NA.2", "NA_2:NA", "NA_2:NA.2")]

  # Extract kinase name from each column (everything before ":")
  kinase_names <- sapply(strsplit(compound_cols, ":"), function(x) x[1])

  # Create unique column names (removing .2 duplicates)
  col_names <- character(length(compound_cols))
  for(i in seq_along(compound_cols)) {
    base_name <- gsub("\\.2$", "", compound_cols[i])
    col_names[i] <- base_name
  }

  # Create unique compound names for final table columns
  unique_compounds <- unique(col_names)

  # Get unique kinases (for vector matching by order)
  unique_kinases <- unique(kinase_names)

  # Extract log concentrations from modified_table and format
  log_concentrations <- as.numeric(modified_table$`log(inhibitor).[M]`[2:12])
  log_concentrations <- format_number(log_concentrations, digits = 2)

  # Define all rows for first column
  rows <- c(
    "Kinase", "nLuc Orientation", "Compound", "Experiment Type (lysed/intact)",
    "Experiment ID", "Cell line", "Construct ID", "Construct ID1",
    "Transfection Mode", "SGC Global Compound ID (Batch)", "LogIC50",
    "IC50, [M]", "IC50 comment", "HillSlope", "R squared", "no. of Y-points",
    "Fit used", "IC50 Curve comment", "Average Positive Ctrl [mBRET]",
    "SD Positive Control [mBRET]", "Average Background [mBRET]",
    "SD Background [mBRET]", "Average luciferase signal",
    "luciferase signal comment", "z'", "Assay window", "Assay window Comment",
    "Assay z' Comment", "Overall Assay Quality comment", "Tracer",
    "Tracer KD, app [M] as log", "Tracer Concentration used [M] (as log)",
    "Tracer  Comment", "Assay volume used [302265L]", "Plate format used",
    "Plate Manufacturer (Catalog No.)", "Plate material used",
    "LOG Compound Concentration 1", "LOG Compound Concentration 2",
    "LOG Compound Concentration 3", "LOG Compound Concentration 4",
    "LOG Compound Concentration 5", "LOG Compound Concentration 6",
    "LOG Compound Concentration 7", "LOG Compound Concentration 8",
    "LOG Compound Concentration 9", "LOG Compound Concentration 10",
    "LOG Compound Concentration 11", "LOG Compound Concentration 12",
    "Compound Concentration 1 BRET", "Compound Concentration 2 BRET",
    "Compound Concentration 3 BRET", "Compound Concentration 4 BRET",
    "Compound Concentration 5 BRET", "Compound Concentration 6 BRET",
    "Compound Concentration 7 BRET", "Compound Concentration 8 BRET",
    "Compound Concentration 9 BRET", "Compound Concentration 10 BRET",
    "Compound Concentration 11 BRET", "Compound Concentration 12 BRET",
    "Compound Concentration 1 BRET-Duplicate",
    "Compound Concentration 2 BRET-Duplicate",
    "Compound Concentration 3 BRET-Duplicate",
    "Compound Concentration 4 BRET-Duplicate",
    "Compound Concentration 5 BRET-Duplicate",
    "Compound Concentration 6 BRET-Duplicate",
    "Compound Concentration 7 BRET-Duplicate",
    "Compound Concentration 8 BRET-Duplicate",
    "Compound Concentration 9 BRET-Duplicate",
    "Compound Concentration 10 BRET-Duplicate",
    "Compound Concentration 11 BRET-Duplicate",
    "Compound Concentration 12 BRET-Duplicate",
    "ELN ID", "Comments", "Date Record Created", "Record Creator"
  )

  # Create base dataframe with first column
  table <- data.frame(
    Field = rows,
    stringsAsFactors = FALSE
  )

  # Create a column for each unique compound
  for(i in seq_along(unique_compounds)) {
    compound <- unique_compounds[i]

    # Find related columns (with and without .2)
    main_col <- compound_cols[which(col_names == compound & !grepl("\\.2$", compound_cols))]
    dup_col <- compound_cols[which(col_names == compound & grepl("\\.2$", compound_cols))]

    # Determine kinase
    kinase <- kinase_names[match(main_col[1], compound_cols)]

    # Get orientation for this specific kinase
    current_orientation <- get_orientation(kinase, nLuc_orientation, unique_kinases)

    # Column name in final_summary
    summary_col_name <- compound

    # Create column data
    col_data <- rep(NA_character_, length(rows))

    # Row 1: Kinase
    col_data[1] <- kinase

    # Row 2: nLuc Orientation - now specific to this kinase
    col_data[2] <- current_orientation

    # Row 3: Compound name (without kinase prefix)
    compound_name <- gsub(paste0("^", kinase, ":"), "", compound)
    col_data[3] <- compound_name

    # Row 4: Experiment Type
    col_data[4] <- experiment_type

    # Row 5: Experiment ID
    col_data[5] <- paste(date, experimenter_abbrev, kinase, compound_name, sep = "-")

    # Row 6: Cell line
    col_data[6] <- cell_line

    # Row 7: Construct ID - GENERATED AUTOMATICALLY based on kinase-specific orientation
    if(toupper(current_orientation) == "N") {
      col_data[7] <- paste0(kinase, "A-nb001")
    } else if(toupper(current_orientation) == "C") {
      col_data[7] <- paste0(kinase, "A-nb002")
    } else {
      col_data[7] <- NA_character_
    }

    # Row 9: Transfection Mode
    col_data[9] <- transfection_mode

    # Row 10: SGC Global Compound ID
    col_data[10] <- as.character(sgc_compound_id)

    # --- INFORMATION FROM FINAL_SUMMARY_TABLE ---
    if(summary_col_name %in% colnames(final_summary)) {

      # Row 11: LogIC50
      log_ic50 <- final_summary["LogIC50", summary_col_name]
      if(!is.na(log_ic50) && log_ic50 != "<NA>") {
        col_data[11] <- format_number(log_ic50, digits = 2)
      }

      # Row 12: IC50, [M]
      ic50 <- final_summary["IC50", summary_col_name]
      if(!is.na(ic50) && ic50 != "<NA>") {
        if(decimal_separator == ",") {
          ic50 <- gsub("\\.", ",", ic50)
        }
        col_data[12] <- ic50
      }

      # Row 14: HillSlope
      hill_slope <- final_summary["Ideal_Hill_Slope", summary_col_name]
      if(!is.na(hill_slope) && hill_slope != "<NA>") {
        col_data[14] <- format_number(hill_slope, digits = 2)
      }

      # Row 15: R squared
      r_squared <- final_summary["R_squared", summary_col_name]
      if(!is.na(r_squared) && r_squared != "<NA>") {
        col_data[15] <- format_number(r_squared, digits = 2)
      }

      # Row 16: no. of Y-points
      degrees_freedom <- final_summary["Degrees_of_Freedom", summary_col_name]
      if(!is.na(degrees_freedom) && degrees_freedom != "<NA>") {
        n_y_points <- as.numeric(degrees_freedom) + 3
        col_data[16] <- as.character(n_y_points)
      }

      # Row 17: Fit used
      col_data[17] <- fit_used

      # Row 18: IC50 Curve comment
      curve_quality <- final_summary["Curve_Quality", summary_col_name]
      if(!is.na(curve_quality) && curve_quality != "<NA>") {
        col_data[18] <- tolower(curve_quality)
      }
    }

    # --- QUALITY INFORMATION (based on kinase) ---
    if(kinase %in% colnames(quality_table)) {

      # Rows 19-29: Quality information
      col_data[19] <- format_number(quality_table["Average_Positive_Ctrl", kinase], digits = 2)
      col_data[20] <- format_number(quality_table["SD_Positive_Ctrl", kinase], digits = 2)
      col_data[21] <- format_number(quality_table["Average_Background", kinase], digits = 2)
      col_data[22] <- format_number(quality_table["SD_Background", kinase], digits = 2)
      col_data[23] <- format_number(quality_table["Average_luciferase_signal", kinase], digits = 2)

      comment_value <- quality_table["Luciferase_signal_comment", kinase]
      if(!is.na(comment_value) && comment_value != "<NA>") {
        col_data[24] <- comment_value
      }

      col_data[25] <- format_number(quality_table["Z_Score", kinase], digits = 2)
      col_data[26] <- format_number(quality_table["Assay_Window", kinase], digits = 2)

      comment_value <- quality_table["Assay_window_Comment", kinase]
      if(!is.na(comment_value) && comment_value != "<NA>") {
        col_data[27] <- comment_value
      }

      comment_value <- quality_table["Assay_z_Comment", kinase]
      if(!is.na(comment_value) && comment_value != "<NA>") {
        col_data[28] <- comment_value
      }

      col_data[29] <- quality_table["Overall_Quality", kinase]
    }

    # Rows 30-33: Tracer information
    col_data[30] <- tracer
    col_data[31] <- format_number(tracer_kd_app, digits = 2)
    col_data[32] <- format_number(tracer_concentration_used, digits = 2)
    col_data[33] <- tracer_comment

    # Rows 34-37: Plate information
    col_data[34] <- assay_volume
    col_data[35] <- plate_format
    col_data[36] <- plate_manufacturer
    col_data[37] <- plate_material

    # Rows 74-77: Metadata
    col_data[74] <- eln_id
    col_data[75] <- comments
    col_data[76] <- date_created
    col_data[77] <- record_creator

    # Fill log concentrations (rows 38-48)
    for(j in 1:length(log_concentrations)) {
      if(j <= 11) {
        col_data[37 + j] <- log_concentrations[j]
      }
    }

    # Fill BRET values (rows 50-61)
    if(length(main_col) > 0) {
      bret_values <- modified_table[[main_col[1]]]
      bret_values <- bret_values[2:(length(bret_values)-1)]

      for(j in 1:length(bret_values)) {
        if(j <= 12) {
          col_data[49 + j] <- format_number(bret_values[j], digits = 4)
        }
      }
    }

    # Fill BRET-Duplicate values (rows 62-73)
    if(length(dup_col) > 0) {
      bret_dup_values <- modified_table[[dup_col[1]]]
      bret_dup_values <- bret_dup_values[2:(length(bret_dup_values)-1)]

      for(j in 1:length(bret_dup_values)) {
        if(j <= 12) {
          col_data[61 + j] <- format_number(bret_dup_values[j], digits = 4)
        }
      }
    }

    # Add column to table
    col_name <- if(i == 1) {
      "X4"
    } else {
      paste0("X", i + 3)
    }

    table[[col_name]] <- col_data
  }

  # Save table if requested
  if(save) {
    if (!requireNamespace("openxlsx", quietly = TRUE)) {
      message("Package 'openxlsx' is needed for saving Excel files. Installing...")
      install.packages("openxlsx")
    }

    if(is.null(file_name)) {
      file_name <- paste0("scarab_table_", plate_name, ".xlsx")
    } else {
      if(!grepl("\\.xlsx$", file_name)) {
        file_name <- paste0(file_name, ".xlsx")
      }
    }

    openxlsx::write.xlsx(table, file = file_name, rowNames = FALSE, colNames = FALSE)
    message(paste("Table saved as:", file_name))
  }

  return(table)
}






